[package]
name = "vfs_nodes"
version = "0.1.0"
authors = ["OvermindDL1 <overminddl1@gmail.com>"]
edition = "2018"

[dependencies]
bevy_app = { version = "0.5", optional = true }
bevy_ecs = { version = "0.5", optional = true }

[features]
bevy = ["bevy_app", "bevy_ecs"]